name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Installation des dépendances
        run: npm install

      - name: Lancement des tests
        run: npm test